CREATE TABLE SCORE(
NUM NUMBER(3),
NAME VARCHAR2(15) NOT NULL,
KOR NUMBER(3),
ENG NUMBER(3),
MAT NUMBER(3),
TOT NUMBER(3)
);

ALTER TABLE SCORE ADD CONSTRAINT pk_num PRIMARY KEY(NUM);

SELECT * FROM SCORE;
SELECT * FROM SCORE;

CREATE SEQUENCE SCO_SEQ INCREMENT BY 1 START WITH 1;

INSERT INTO SCORE VALUES(100, '김민걸', 100, 100, 100, 100);